
USE ACCOMEDY

DROP TABLE IF EXISTS [dbo].[POSTS]
DROP TABLE IF EXISTS [dbo].[USERS]
DROP TABLE IF EXISTS [dbo].[ROLES]
DROP TABLE IF EXISTS [dbo].[USER_ROLES]
DROP TABLE IF EXISTS [dbo].[USER_POSTS]

CREATE TABLE [dbo].[ROLES]
(
	ROLE_CODE VARCHAR(128) NOT NULL
	,ROLE_NAME VARCHAR(128) NOT NULL
	,PRIMARY KEY (ROLE_CODE)
)

CREATE TABLE [dbo].[USERS]
(
	USER_ID UNIQUEIDENTIFIER NOT NULL
	,USER_NAME VARCHAR(128) NOT NULL
	,FIRST_NAME VARCHAR(128) NOT NULL
	,LAST_NAME VARCHAR(128) NOT NULL
	,EMAIL VARCHAR(128) NOT NULL
	,ADDRESS VARCHAR(128) NOT NULL
	,PHONE VARCHAR(128) NOT NULL
	,PRIMARY KEY (USER_ID)
)

CREATE TABLE [dbo].[USER_ROLES]
(
	USER_ID UNIQUEIDENTIFIER NOT NULL
	,ROLE_CODE VARCHAR(128) NOT NULL
	FOREIGN KEY (ROLE_CODE) REFERENCES dbo.ROLES (ROLE_CODE),
	FOREIGN KEY (USER_ID) REFERENCES dbo.USERS (USER_ID)
)

CREATE TABLE [dbo].[POSTS]
(
	POST_ID UNIQUEIDENTIFIER NOT NULL
	,TITLE VARCHAR(128) NOT NULL
	,DETAILS VARCHAR(MAX) NOT NULL
	,PHOTOS VARCHAR(128) NOT NULL
	,PRICE DECIMAL(10,2) NOT NULL
	,ADDRESS VARCHAR(128) NOT NULL
	,STATUS VARCHAR(128)
	,PRIMARY KEY (POST_ID)
);

CREATE TABLE [dbo].[USER_POSTS]
(
	USER_ID UNIQUEIDENTIFIER NOT NULL
	,POST_ID UNIQUEIDENTIFIER NOT NULL
	FOREIGN KEY (POST_ID) REFERENCES dbo.POSTS (POST_ID),
	FOREIGN KEY (USER_ID) REFERENCES dbo.USERS (USER_ID)
)
